---

- name: Create folder to clone GeoTrellis into
  file: path=/opt/geotrellis
        owner=ubuntu
        group=ubuntu
        state=directory
        mode=0777

- name: Clone GeoTrellis repository
  git: repo=https://github.com/geotrellis/geotrellis.git
       dest=/opt/geotrellis
       update=yes
       depth=1
  sudo: no

- name: Run Publish Local to place locally
  command: ./sbt -mem 4000 "project macros" publish-local "project vector" publish-local "project proj4" publish-local "project raster" publish-local "project engine"
           chdir=/opt/geotrellis
  sudo: no
